import os
from dotenv import load_dotenv

load_dotenv()

# --- Posture Thresholds ---
FHP_THRESHOLD = 1.05
SHOULDER_ASYMMETRY_THRESHOLD = 2
HEAD_TILT_THRESHOLD = 3
NORMALIZED_DROP_THRESHOLD = 0.05
LOOKING_DOWN_THRESHOLD = 0.5

# --- Timing & Smoothing ---
SMOOTHING_WINDOW = 10 
GRACE_PERIOD_SECONDS = 7.0
PROLONGED_GRACE_PERIOD_SECONDS = 180.0
ABSENCE_THRESHOLD = 5.0
NOTIFICATION_THRESHOLD_SECONDS = 30

# --- Camera Settings ---
CAMERA_WIDTH = 1280
CAMERA_HEIGHT = 720

# --- Firebase ---
FIREBASE_DB_URL = os.getenv("FIREBASE_DB_URL")
DEVICE_ID = os.getenv("DEVICE_ID", "pi_desk_001")
USER_UID = os.getenv("USER_UID")

# --- Status and Colors ---
class Colors:
	OK = (0, 255, 0)
	WARNING = (0, 165, 255)
	CRITICAL = (0, 0, 255)
	INFO = (200, 200, 200)
	PAUSED = (0, 255, 255)
	
class Status:
	OK = "Posture OK"
	FHP = "FHP"
	SLOUCHING = "SLOUCHING"
	ASYMMETRIC_SHOULDERS = "ASYMMETRIC SHOULDERS"
	HEAD_TILTED = "HEAD TILTED"
	HEAD_TURNED = "HEAD TURNED"
	LOOKING_DOWN = "LOOKING DOWN"
	UNCALIBRATED = "UNCALIBRATED"
	SEARCHING = "SEARCHING"
	IDLE = "IDLE"

# Types of Status:

ACUTE_STATUSES = [
    Status.SLOUCHING, 
    Status.FHP, 
    Status.ASYMMETRIC_SHOULDERS, 
    Status.HEAD_TILTED
]
PROLONGED_STATUSES = [
    Status.LOOKING_DOWN, 
    Status.HEAD_TURNED
]
