import os
from dotenv import load_dotenv

load_dotenv()

# --- Posture Thresholds ---
FHP_THRESHOLD = 1.05
SLOUCHING_THRESHOLD = 0.75
SLOUCHING_FHP_MIN_THRESHOLD = 1.03
SHOULDER_ASYMMETRY_THRESHOLD = 2
HEAD_TILT_THRESHOLD = 3

# --- Timing & Smoothing ---
SMOOTHING_WINDOW = 10 
GRACE_PERIOD_SECONDS = 7.0
ABSENCE_THRESHOLD = 5.0
NOTIFICATION_THRESHOLD_SECONDS = 30
CAMERA_FPS = 10
NOTIFICATION_THRESHOLD_FRAMES = NOTIFICATION_THRESHOLD_SECONDS * CAMERA_FPS

# --- Camera Settings ---
CAMERA_WIDTH = 1280
CAMERA_HEIGHT = 720

# --- Firebase ---
FIREBASE_DB_URL = os.getenv("FIREBASE_DB_URL")
DEVICE_ID = os.getenv("DEVICE_ID", "pi_desk_001")
USER_UID = os.getenv("USER_UID")

# --- Status and Colors ---
class Colors:
	OK = (0, 255, 0)
	WARNING = (0, 165, 255)
	CRITICAL = (0, 0, 255)
	INFO = (200, 200, 200)
	PAUSED = (0, 255, 255)
	
class Status:
	OK = "Posture OK"
	FHP = "FHP"
	SLOUCHING = "SLOUCHING"
	ASYMMETRIC_SHOULDERS = "ASYMMETRIC SHOULDERS"
	HEAD_TILTED = "HEAD TILTED"
	HEAD_TURNED = "HEAD TURNED"
	UNCALIBRATED = "UNCALIBRATED"
	SEARCHING = "SEARCHING"
	IDLE = "IDLE"

